version: "3.7"

services:
  node-dev-server:
      image: "node:12"
      user: "node"
      working_dir: /usr/src/app
      expose:
        - "8080"
      command: "yarn install"
      command: "yarn start"
      container_name: "dev-server"
      ports:
        - "8080:8080"
      volumes:
        - ./server:/usr/src/app
        - /server/usr/src/app/node_modules
      depends_on:
        - db
  db:
    container_name: course-db
    image: postgres:latest
    restart: always
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: course-db
    ports:
      - 5560:5432
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
  # pgadmin-compose:
  #   image: dpage/pgadmin4:4.28
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "test@gmail.com"
  #     PGADMIN_DEFAULT_PASSWORD: "test123!"
  #   ports:
  #     - "16543:80"
  #   depends_on:
  #     - db
volumes:
  node_modules:
